name: run generate.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
env:
  RSS_URL: ${{ secrets.RSS_URL }} 
  GIT_USER: ${{ secrets.GIT_USER }} 
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }} 
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: pip install -r requirements.txt
    - run: |
        echo $RSS_URL
        python generate.py
      env:
        RSS_URL: ${{ secrets.RSS_URL }} 
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: $GIT_USER  
        user_email: $GIT_EMAIL  
        commit_msg: ${{ github.event.head_commit.message }}  
